# Generated by Django 5.0.1 on 2024-02-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_elasticdemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('pitcher', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pitcher_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('company_name', models.CharField(max_length=100)),
                ('ask_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('equity_in_percentage', models.FloatField(blank=True, null=True)),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_deal_approve', models.BooleanField(default=False)),
                ('contestants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.pitcher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sharks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('shark_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('shark_image', models.ImageField(blank=True, null=True, upload_to='team')),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ElasticDemo',
        ),
    ]
